### PR TITLE
Add support for anchors

### PR DESCRIPTION
**Pull request by roylodder**
Added a new option to support the anchor setting.

### CODE REVIEW

**Comment by palmiak** [comment]
thanks @roylodder I missed that one :)  

Could you also update the `readme.md` example with this? Than I can merge it

**Comment by palmiak** [comment]
Thanks @roylodder - merging it to master.

**Comment by roylodder** [comment]
Thanks! Had some personal stuff to deal with and no time to reply.

**Comment by palmiak** [comment]
No problem. Nice to see people are using this 😀

czw., 25 lip 2019, 12:22 użytkownik Roy Lodder <notifications@github.com>
napisał:

**Pull request merged**
